import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Users, UserPlus, Search, Store, UserCheck, Link2Off, RefreshCw, MoreHorizontal, Eye, KeyRound, Power, Trash2, Loader2, ExternalLink, ChevronRight, ChevronLeft, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PasswordInput } from "@/components/PasswordInput";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { toast } from "@/hooks/use-toast";
import { accountLabels, statusLabels, fetchAdminUsers, manageAdminUser, type DirectoryFilters, type DirectoryUser, type UserStoreLink } from "@/lib/adminUsers";

const defaults: DirectoryFilters = { search: "", kind: "all", status: "all", link: "all", sort: "newest", page: 1 };
const date = (value: string | null, time = false) => value ? new Date(value).toLocaleString("ar-LY", { year: "numeric", month: "short", day: "numeric", ...(time ? { hour: "2-digit", minute: "2-digit" } as const : {}) }) : "لم يسجّل الدخول بعد";
const relationLabel = { owner: "مالك", staff: "موظف", courier: "مندوب" };

function StoreLink({ store }: { store: UserStoreLink }) {
  return <a href={`/store/${encodeURIComponent(store.slug)}`} target="_blank" rel="noopener noreferrer" className="inline-flex max-w-full items-center gap-1.5 rounded-md border bg-background px-2 py-1 text-xs hover:border-primary/50 hover:text-primary" title={`فتح متجر ${store.name}`}>
    <Store className="h-3 w-3 shrink-0" /><span className="truncate max-w-48">{store.name}</span><span className="text-muted-foreground">· {relationLabel[store.relation]}</span><ExternalLink className="h-3 w-3 shrink-0" />
  </a>;
}

export default function AdminUserDirectory() {
  const cache = useQueryClient();
  const [search, setSearch] = useState("");
  const [filters, setFilters] = useState(defaults);
  const [selected, setSelected] = useState<DirectoryUser | null>(null);
  const [action, setAction] = useState<{ type: "reset_password" | "toggle_active" | "delete"; user: DirectoryUser } | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [form, setForm] = useState({ username: "", full_name: "", email: "", password: "" });
  const [password, setPassword] = useState("");
  const [confirmUsername, setConfirmUsername] = useState("");
  const [saving, setSaving] = useState(false);
  const [mutationError, setMutationError] = useState("");
  useEffect(() => { const timer = setTimeout(() => setFilters(f => f.search === search.trim() ? f : ({ ...f, search: search.trim(), page: 1 })), 300); return () => clearTimeout(timer); }, [search]);
  const query = useQuery({ queryKey: ["admin-user-directory", filters], queryFn: ({ signal }) => fetchAdminUsers(filters, signal), staleTime: 30_000, retry: 1 });
  const data = query.data;
  const change = (key: keyof DirectoryFilters, value: string) => setFilters(f => ({ ...f, [key]: value, page: 1 }));
  const resetFilters = () => { setSearch(""); setFilters(defaults); };
  const filtered = !!(search || filters.kind !== "all" || filters.status !== "all" || filters.link !== "all");
  const refresh = () => cache.invalidateQueries({ queryKey: ["admin-user-directory"] });
  const begin = (type: "reset_password" | "toggle_active" | "delete", user: DirectoryUser) => { setAction({ type, user }); setPassword(""); setConfirmUsername(""); setMutationError(""); };
  async function save(create = false) {
    setSaving(true); setMutationError("");
    try {
      if (create) await manageAdminUser("create", { ...form, email: form.email.trim(), username: form.username.trim() });
      else if (action) await manageAdminUser(action.type, { user_id: action.user.user_id, new_password: password, is_active: action.user.profile_active === false });
      toast({ title: "تم", description: create ? "تم إنشاء المستخدم ومتجره" : "تم حفظ التغيير" });
      if (create) { setCreateOpen(false); setForm({ username: "", full_name: "", email: "", password: "" }); }
      else setAction(null);
      void refresh();
    } catch (e) { setMutationError(e instanceof Error ? e.message : "تعذّر تنفيذ العملية"); }
    finally { setSaving(false); }
  }
  const status = (u: DirectoryUser) => <Badge variant="outline" className={u.status === "active" ? "border-emerald-500/25 bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" : u.status === "disabled" ? "border-destructive/25 bg-destructive/10 text-destructive" : "border-amber-500/25 bg-amber-500/10 text-amber-600 dark:text-amber-400"}>{statusLabels[u.status]}</Badge>;
  const identity = (u: DirectoryUser) => <div className="flex items-center gap-3 min-w-0"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 font-bold text-primary">{(u.full_name || u.username || "؟").slice(0, 1)}</div><div className="min-w-0"><button type="button" onClick={() => setSelected(u)} className="max-w-full truncate font-semibold text-start hover:text-primary">{u.full_name || u.username || "بدون اسم"}</button><p className="text-xs text-muted-foreground truncate"><bdi>@{u.username}</bdi></p><p className="text-xs text-muted-foreground truncate max-w-56"><bdi>{u.email || "حساب باسم مستخدم"}</bdi></p></div></div>;
  const storeSummary = (u: DirectoryUser) => <div className="space-y-1.5">{u.kind === "admin" && <p className="text-xs text-primary flex items-center gap-1"><ShieldCheck className="w-3 h-3" /> صلاحية على كل المتاجر</p>}{u.stores.slice(0, 2).map(s => <div key={`${s.id}-${s.relation}`}><StoreLink store={s} /></div>)}{u.stores.length > 2 && <button className="text-xs text-primary hover:underline" onClick={() => setSelected(u)}>عرض {u.stores.length - 2} ارتباطات أخرى</button>}{!u.stores.length && u.kind !== "admin" && <span className="text-xs text-amber-600 dark:text-amber-400">غير مرتبط بمتجر</span>}</div>;
  const actions = (u: DirectoryUser) => <DropdownMenu dir="rtl"><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" aria-label={`إجراءات ${u.username}`}><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => setSelected(u)}><Eye className="ml-2 h-4 w-4" /> تفاصيل المستخدم</DropdownMenuItem>{u.kind !== "admin" && <DropdownMenuItem onSelect={() => begin("reset_password", u)}><KeyRound className="ml-2 h-4 w-4" /> تغيير كلمة المرور</DropdownMenuItem>}{u.has_profile && ["owner", "unassigned"].includes(u.kind) && <><DropdownMenuItem onSelect={() => begin("toggle_active", u)}><Power className="ml-2 h-4 w-4" />{u.profile_active === false ? "تفعيل الحساب" : "تعطيل الحساب"}</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-destructive focus:text-destructive" onSelect={() => begin("delete", u)}><Trash2 className="ml-2 h-4 w-4" /> حذف الحساب</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu>;

  return <section className="space-y-5" aria-label="دليل المستخدمين">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">المستخدمون والمتاجر</h2><p className="text-sm text-muted-foreground mt-1">كل حساب، دوره، والمتاجر المرتبط بها في مكان واحد.</p></div><div className="flex gap-2"><Button variant="outline" size="icon" aria-label="تحديث قائمة المستخدمين" disabled={query.isFetching} onClick={() => void refresh()}><RefreshCw className={`h-4 w-4 ${query.isFetching ? "animate-spin" : ""}`} /></Button><Button className="gap-2" onClick={() => { setMutationError(""); setCreateOpen(true); }}><UserPlus className="h-4 w-4" /> إضافة مستخدم</Button></div></div>
    <div className="grid grid-cols-2 xl:grid-cols-4 gap-3">{[
      { label: "إجمالي المستخدمين", value: data?.summary.total, note: "جميع أنواع الحسابات", icon: Users, color: "text-primary bg-primary/10" },
      { label: "الحسابات النشطة", value: data?.summary.active, note: "مؤكدة وغير معطّلة", icon: UserCheck, color: "text-emerald-600 bg-emerald-500/10" },
      { label: "أصحاب المتاجر", value: data?.summary.owners, note: data ? `${data.summary.staff} موظف · ${data.summary.couriers} مندوب` : "—", icon: Store, color: "text-sky-600 bg-sky-500/10" },
      { label: "بدون ارتباط بمتجر", value: data?.summary.unlinked, note: "باستثناء حسابات السوبر أدمن", icon: Link2Off, color: "text-amber-600 bg-amber-500/10" },
    ].map(item => <div key={item.label} className="rounded-xl border bg-card p-4"><div className="flex justify-between items-start gap-2"><span className="text-xs sm:text-sm text-muted-foreground">{item.label}</span><item.icon className={`h-8 w-8 rounded-lg p-1.5 shrink-0 ${item.color}`} /></div><p className="text-3xl font-bold tabular-nums mt-1">{item.value ?? "—"}</p><p className="text-xs text-muted-foreground mt-2">{item.note}</p></div>)}</div>
    <div className="rounded-xl border bg-card overflow-hidden">
      <div className="p-4 space-y-3 border-b bg-muted/20"><div className="relative"><Search className="absolute right-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={e => setSearch(e.target.value)} maxLength={120} className="pr-9 bg-background" aria-label="البحث في المستخدمين والمتاجر" placeholder="ابحث بالاسم، اسم المستخدم، البريد أو اسم المتجر..." /></div>
        <div className="flex flex-wrap gap-2">{[
          { key: "kind" as const, label: "نوع الحساب", items: [["all", "كل أنواع الحسابات"], ...Object.entries(accountLabels)] },
          { key: "status" as const, label: "حالة الحساب", items: [["all", "كل الحالات"], ...Object.entries(statusLabels)] },
          { key: "link" as const, label: "ارتباط المتجر", items: [["all", "كل الارتباطات"], ["linked", "مرتبط بمتجر"], ["unlinked", "بدون ارتباط"]] },
          { key: "sort" as const, label: "ترتيب المستخدمين", items: [["newest", "الأحدث تسجيلًا"], ["oldest", "الأقدم تسجيلًا"], ["last_sign_in", "آخر تسجيل دخول"]] },
        ].map(filter => <Select key={filter.key} value={filters[filter.key]} onValueChange={v => change(filter.key, v)} dir="rtl"><SelectTrigger aria-label={filter.label} className="w-full sm:w-44 bg-background"><SelectValue /></SelectTrigger><SelectContent>{filter.items.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select>)}{filtered && <Button variant="ghost" onClick={resetFilters}>مسح الفلاتر</Button>}</div>
      </div>
      {query.isError ? <div role="alert" className="p-8 text-center space-y-3"><p className="text-destructive">تعذّر تحميل المستخدمين: {query.error.message}</p><Button variant="outline" onClick={() => void query.refetch()}>إعادة المحاولة</Button></div> : !data ? <div role="status" className="p-12 flex justify-center gap-2 text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" /> جاري تحميل المستخدمين...</div> : !data.users.length ? <div className="p-12 text-center"><Users className="mx-auto h-9 w-9 text-muted-foreground mb-3" /><p className="font-semibold">{filtered ? "لا يوجد مستخدمون مطابقون للبحث" : "لا يوجد مستخدمون بعد"}</p><p className="text-sm text-muted-foreground mt-2">{filtered ? "جرّب اسم المتجر أو غيّر الفلاتر." : "أضف أول مستخدم من الزر أعلاه."}</p></div> : <>
        <div className="hidden md:block overflow-x-auto"><table className="w-full text-sm text-right"><thead className="bg-muted/30 text-xs text-muted-foreground"><tr>{["المستخدم", "نوع الحساب", "المتاجر المرتبطة", "الحالة", "آخر دخول", ""].map((h, i) => <th key={i} scope="col" className="p-4 font-medium">{h || <span className="sr-only">الإجراءات</span>}</th>)}</tr></thead><tbody className="divide-y">{data.users.map(u => <tr key={u.user_id} className="hover:bg-muted/20 transition-colors"><td className="p-4">{identity(u)}</td><td className="p-4"><Badge variant="secondary" className="whitespace-nowrap">{accountLabels[u.kind]}</Badge>{u.permission_group && <p className="text-xs text-muted-foreground mt-2">{u.permission_group}</p>}</td><td className="p-4">{storeSummary(u)}</td><td className="p-4">{status(u)}</td><td className="p-4 text-xs text-muted-foreground whitespace-nowrap">{date(u.last_sign_in_at)}<p className="mt-2">انضم {date(u.created_at)}</p></td><td className="p-2">{actions(u)}</td></tr>)}</tbody></table></div>
        <div className="md:hidden divide-y">{data.users.map(u => <article key={u.user_id} className="p-4 space-y-3"><div className="flex justify-between gap-2">{identity(u)}{actions(u)}</div><div className="flex flex-wrap gap-2"><Badge variant="secondary">{accountLabels[u.kind]}</Badge>{status(u)}</div>{storeSummary(u)}<p className="text-xs text-muted-foreground">آخر دخول: {date(u.last_sign_in_at)}</p></article>)}</div>
      </>}
      {data && <div className="flex flex-wrap items-center justify-between gap-3 border-t px-4 py-3 text-xs text-muted-foreground"><span role="status">{data.total ? `${(data.page-1)*data.page_size+1}–${Math.min(data.page*data.page_size,data.total)} من ${data.total} مستخدم` : "0 مستخدم"}{filtered ? " حسب الفلاتر" : ""}</span><div className="flex items-center gap-2"><Button size="icon" variant="outline" aria-label="الصفحة السابقة" disabled={data.page <= 1 || query.isFetching} onClick={() => setFilters(f => ({ ...f, page: data.page-1 }))}><ChevronRight className="h-4 w-4" /></Button><span>صفحة {data.page} من {Math.max(1,Math.ceil(data.total/data.page_size))}</span><Button size="icon" variant="outline" aria-label="الصفحة التالية" disabled={data.page*data.page_size >= data.total || query.isFetching} onClick={() => setFilters(f => ({ ...f, page: data.page+1 }))}><ChevronLeft className="h-4 w-4" /></Button></div></div>}
    </div>
    <Dialog open={!!selected} onOpenChange={o => !o && setSelected(null)}><DialogContent dir="rtl" className="max-w-2xl max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>تفاصيل المستخدم</DialogTitle><DialogDescription>بيانات الحساب وارتباطاته الفعلية بالمتاجر.</DialogDescription></DialogHeader>{selected && <div className="space-y-5"><div className="rounded-lg bg-muted/40 p-4 space-y-3">{identity(selected)}<div className="flex gap-2"><Badge variant="secondary">{accountLabels[selected.kind]}</Badge>{status(selected)}</div><dl className="grid sm:grid-cols-2 gap-3 text-sm"><div><dt className="text-muted-foreground">تاريخ التسجيل</dt><dd>{date(selected.created_at,true)}</dd></div><div><dt className="text-muted-foreground">آخر تسجيل دخول</dt><dd>{date(selected.last_sign_in_at,true)}</dd></div><div className="sm:col-span-2"><dt className="text-muted-foreground">معرّف الحساب</dt><dd className="font-mono text-xs break-all" dir="ltr">{selected.user_id}</dd></div></dl></div>{selected.kind === "admin" && <p className="text-sm text-primary">لديه صلاحية إدارة جميع المتاجر. الارتباطات التالية توضّح المتاجر المسجلة على حسابه.</p>}<h3 className="font-semibold">المتاجر المرتبطة ({selected.stores.length})</h3>{selected.stores.map(s => <div key={`${s.id}-${s.relation}`} className="rounded-lg border p-3 space-y-2"><StoreLink store={s} /><p className="text-xs text-muted-foreground">مالك المتجر: {s.owner_name || "غير محدد"}{s.group_name ? ` · مجموعة الصلاحيات: ${s.group_name}` : ""}</p><Link className="inline-block text-xs text-primary hover:underline" to={`/dashboard/stores/${s.owner_id}`}>عرض بيانات حساب مالك المتجر</Link></div>)}{!selected.stores.length && <p className="text-sm text-muted-foreground">لا توجد متاجر مرتبطة بهذا الحساب.</p>}</div>}</DialogContent></Dialog>
    <Dialog open={createOpen} onOpenChange={o => !saving && setCreateOpen(o)}><DialogContent dir="rtl"><DialogHeader><DialogTitle>إضافة مستخدم جديد</DialogTitle><DialogDescription>إنشاء حساب مالك متجر. إضافة الموظفين والمناديب تتم من واجهاتهم داخل المتجر.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e => { e.preventDefault(); void save(true); }}>{[
      { key: "full_name" as const, label: "الاسم الكامل (اختياري)", type: "text", required: false },
      { key: "username" as const, label: "اسم المستخدم", type: "text", required: true },
      { key: "email" as const, label: "البريد الإلكتروني", type: "email", required: true },
    ].map(field => <div key={field.key} className="space-y-2"><Label htmlFor={`admin-${field.key}`}>{field.label}</Label><Input id={`admin-${field.key}`} type={field.type} required={field.required} autoComplete="off" dir={field.key === "full_name" ? "rtl" : "ltr"} pattern={field.key === "username" ? "[a-z0-9_-]{3,50}" : undefined} title={field.key === "username" ? "من 3 إلى 50 حرفًا إنجليزيًا صغيرًا أو رقمًا أو _ أو -" : undefined} value={form[field.key]} onChange={e => setForm(f => ({ ...f, [field.key]: field.key === "username" ? e.target.value.toLowerCase() : e.target.value }))} /></div>)}<div className="space-y-2"><Label htmlFor="admin-create-password">كلمة المرور</Label><PasswordInput id="admin-create-password" minLength={8} maxLength={128} required autoComplete="new-password" value={form.password} onChange={e => setForm(f => ({ ...f, password: e.target.value }))} /></div>{mutationError && <p role="alert" className="text-sm text-destructive">{mutationError}</p>}<Button className="w-full" disabled={saving} type="submit">{saving ? <Loader2 className="w-4 h-4 animate-spin" /> : "إنشاء المستخدم"}</Button></form></DialogContent></Dialog>
    <Dialog open={!!action} onOpenChange={o => !o && !saving && setAction(null)}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{action?.type === "reset_password" ? "تغيير كلمة المرور" : action?.type === "delete" ? "حذف الحساب نهائيًا" : action?.user.profile_active === false ? "تفعيل الحساب" : "تعطيل الحساب"}</DialogTitle><DialogDescription>{action?.user.full_name || action?.user.username} · @{action?.user.username}</DialogDescription></DialogHeader><form onSubmit={e => { e.preventDefault(); void save(); }} className="space-y-4">{action?.type === "reset_password" ? <div className="space-y-2"><Label htmlFor="admin-reset-password">كلمة المرور الجديدة</Label><PasswordInput id="admin-reset-password" value={password} onChange={e => setPassword(e.target.value)} minLength={8} maxLength={128} autoComplete="new-password" required /></div> : action?.type === "delete" ? <><p className="text-sm text-destructive">سيُحذف الحساب وبياناته المرتبطة نهائيًا. لا يمكن التراجع عن العملية.</p><Label htmlFor="admin-confirm-username">اكتب المعرّف للتأكيد: <bdi>{action.user.username || action.user.user_id}</bdi></Label><Input id="admin-confirm-username" dir="ltr" value={confirmUsername} onChange={e => setConfirmUsername(e.target.value)} autoComplete="off" /></> : <p className="text-sm text-muted-foreground">سيتم تغيير حالة حساب مالك المتجر، وقد يتأثر وصول الموظفين المرتبطين به.</p>}{mutationError && <p role="alert" className="text-sm text-destructive">{mutationError}</p>}<div className="flex gap-2"><Button type="submit" variant={action?.type === "delete" ? "destructive" : "default"} disabled={saving || (action?.type === "delete" && confirmUsername !== (action.user.username || action.user.user_id))}>{saving ? <Loader2 className="w-4 h-4 animate-spin" /> : "تأكيد"}</Button><Button type="button" variant="outline" disabled={saving} onClick={() => setAction(null)}>إلغاء</Button></div></form></DialogContent></Dialog>
  </section>;
}
